HelloApplication/Models/Paging.cs
using System.Collections.Generic;

namespace HelloApplication.Models
{
    public class Paging
    {
        public int CurrentPage { get; set; }
        public int LastPage { get; set; }
        public List<int> Pages { get; set; }
        public string ControllerName { get; set; }
    }
}

HelloApplication/Controllers/GuestBookController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using HelloApplication.Context;
using HelloApplication.Models;

namespace HelloApplication.Controllers
{
    public class GuestBookController : Controller
    {
        // GET: GuestBook
        public ActionResult Index(int page = 1)
        {
            var messages = new List<Message>();
            int count;
            using (var db = new MessagesContext())
            {
                /*db.Database.Log = (string message) =>
                {
                    using (var file = System.IO.File.AppendText(@"c:\temp\log.sql"))
                    {
                        file.WriteLine(message);
                    }
                };*/

                messages = db.Messages
                    .OrderByDescending(m => m.Id)
                    .Skip((page - 1) * Constants.PageSize)
                    .Take(Constants.PageSize)
                    .Select(m => new Message
                    {
                        Id = m.Id,
                        Post = m.Post
                    }).ToList();
                count = db.Messages.Count();
            }

            ViewBag.CurrentPage = page;
            ViewBag.Count = count;
            ViewBag.ControllerName = ControllerContext.RouteData.Values["controller"].ToString();

            return View(messages);
        }

        //[Authorize]
        public PartialViewResult Post()
        {            
            return PartialView("Post");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Post(Message message)
        {
            if (ModelState.IsValid)
            {
                using (var db = new MessagesContext())
                {
                    db.Messages.Add(new Entities.MessageEntity
                    {
                        Post = message.Post
                    });
                    db.SaveChanges();
                }
            }           

            return RedirectToAction("Index");
        }        
    }
}

HelloApplication/Controllers/PagingController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using HelloApplication.Models;

namespace HelloApplication.Controllers
{
    public class PagingController : Controller
    {
        [ChildActionOnly]
        public PartialViewResult Paging(int currentPage, int count, string controllerName)
        {
            var countPages = (int)Math.Ceiling((double)count / Constants.PageSize);
            if (currentPage > countPages)
            {
                currentPage = countPages;
            }
            else if (currentPage < 1)
            {
                currentPage = 1;
            }

            var paging = new Paging
            {
                CurrentPage = currentPage,
                LastPage = countPages,
                ControllerName = controllerName
            };


            /*var pages = new List<int>();
            if (currentPage == 1)
            {
                pages.Add(1);
                var minPage = Math.Min(MaxCountLinks, countPages);
                for (var i = 2; i < minPage; i++)
                {
                    pages.Add(i);
                }
            }
            else if (currentPage == countPages)
            {
                var firstPage = Math.Max(1, currentPage - MaxCountLinks);
                for (var i = firstPage; i < currentPage; i++)
                {
                    pages.Add(i);
                }
            }
            else
            {
                pages.Add(currentPage - 1);
                pages.Add(currentPage);
                pages.Add(currentPage + 1);
            }*/

            var pages = new List<int>();
            if (currentPage == 1)
            {
                pages.Add(currentPage);
                var minPage = Math.Min(Constants.MaxCountLinks, countPages);
                for (var i = 2; i <= minPage; i++)
                {
                    pages.Add(i);
                }
            }
            else if (currentPage == countPages)
            {                
                var firstPage = Math.Max(1, currentPage - Constants.MaxCountLinks);
                for (var i = firstPage; i < currentPage; i++)
                {
                    pages.Add(i);
                }
                pages.Add(currentPage);
            }
            else
            {
                var halfCount = (int)Math.Floor((double)Constants.MaxCountLinks / 2);
                var firstLink = Math.Max(1, currentPage - halfCount);
                for (var i = firstLink; i <= currentPage; i++)
                {
                    pages.Add(i);
                }
                var otherHalfCount = Constants.MaxCountLinks - halfCount;
                var lastLink = Math.Min(currentPage + otherHalfCount, countPages);
                for (var i = currentPage + 1; i <= lastLink; i++)
                {
                    pages.Add(i);
                }
            }
            paging.Pages = pages;

            return PartialView(paging);
        }
    }
}

HelloApplication/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HelloApplication.Context;
using HelloApplication.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using HelloApplication.Filters;

namespace HelloApplication.Controllers
{
    [MyUnauthorized(Users = Constants.MainUser)]
    public class UsersController : Controller
    {
        private readonly int _pageSize = int.Parse(ConfigurationManager.AppSettings["UsersPage"]);

        // GET: Users
        public ActionResult Index(int page = 1)
        {
            using (var context = new MessagesContext())
            {
                var store = new UserStore<ApplicationUser>(context);
                var manager = new UserManager<ApplicationUser>(store);

                var users = context.Users.OrderBy(u => u.UserName == Constants.MainUser ? "" : u.UserName)
                    .Skip((page - 1) * _pageSize)
                    .Take(_pageSize).ToList().Select(u => new User
                    {
                        Id = u.Id,
                        IsAdmin = manager.IsInRole(u.Id, Constants.Roles.AdminRole),
                        UserName = u.UserName
                    }).ToList();

                /*var users = new List<User>();
                var n = 65;
                for (var i = 0; i <= n; i++)
                {
                    users.Add(new User
                    {
                        Id = i.ToString(),
                        UserName = $"oleg_{i}",
                    });
                }

                users = users.Skip((page - 1) * _pageSize).Take(_pageSize).ToList();*/
                ViewBag.CurrentPage = page;
                ViewBag.Count = context.Users.Count();
                ViewBag.ControllerName = ControllerContext.RouteData.Values["controller"].ToString();

                return View(users);
            }
        }        
       
        // POST: Users/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public void Update(string id, bool isAdmin)
        {
            try
            {
                using (var context = new MessagesContext())
                {
                    var store = new UserStore<ApplicationUser>(context);
                    var manager = new UserManager<ApplicationUser>(store);

                    if (isAdmin)
                    {
                        manager.AddToRole(id, Constants.Roles.AdminRole);
                    }
                    else
                    {
                        manager.RemoveFromRole(id, Constants.Roles.AdminRole);
                    }
                }
            }
            catch (Exception)
            {
                throw new Exception("Произошла некоторая ошибка");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            try
            {
                using (var context = new MessagesContext())
                {
                    var store = new UserStore<ApplicationUser>(context);
                    var manager = new UserManager<ApplicationUser>(store);
                    var user = manager.FindById(id);
                    manager.Delete(user);
                }
            }
            catch (Exception)
            {
                throw new Exception("Произошла некоторая ошибка");
            }
            return RedirectToAction("Index");
        }
    }
}

HelloApplication/Views/Shared/Paging.cshtml
@model HelloApplication.Models.Paging  

@if (Model.Pages.Count > 1)
{
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            @if (Model.CurrentPage != 1)
            {
                <li class="page-item">
                    <a class="page-link" href="@(Url.Action("Index", Model.ControllerName, new {page = Model.CurrentPage - 1}))">Предыдущий</a>
                </li>
            }
            @foreach (var page in Model.Pages)
            {
                <li class="page-item @(page == Model.CurrentPage ? "active" : "")" }>
                    <a class="page-link" href="@(Url.Action("Index", Model.ControllerName, new {page}))">@page</a>
                </li>
            }
            @if ((Model.CurrentPage + 1) <= Model.LastPage)
            {
                <li class="page-item">
                    <a class="page-link" href="@(Url.Action("Index", Model.ControllerName, new {page = Model.CurrentPage + 1}))">Следующий</a>
                </li>
            }
        </ul>
    </nav>
}

HelloApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
        }({
            instrumentationKey:"392a6de8-c509-436c-bcfc-dae58426d8ea"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Гостевая книга", "Index", "GuestBook", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @{if (User.Identity.Name == Constants.MainUser)
                    {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Пользователи", "Index", "Users")</li>
                    </ul>
                        }
                    }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")    
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/guestbook")
    @RenderSection("scripts", required: false)
</body>
</html>